import type { CardDefinition } from "../types";

// ---------------------------------------------------------------------------
// QIN (15 cards) — High power, direct removal, pressure, beginner-friendly.
// ---------------------------------------------------------------------------

const qinCards: CardDefinition[] = [
  // ── existing: pure bodies ─────────────────────────────────────────────────
  {
    id: "qin-infantry",
    name: "Qin Infantry",
    englishName: "Qin Infantry",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 5,
    description: "A dependable Qin melee unit with straightforward power.",
  },
  {
    id: "qin-veteran",
    name: "Qin Veteran",
    englishName: "Qin Veteran",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 6,
    description: "A hardened Qin front-line unit built for steady pressure.",
  },
  {
    id: "iron-eagle-soldier",
    name: "Iron Eagle Soldier",
    englishName: "Iron Eagle Soldier",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 8,
    rarity: "elite",
    tags: ["soldier", "elite"],
    effects: [],
    budget: 8,
    description: "An elite Qin attacker with high standalone strength.",
  },
  // ── existing: skill cards (updated) ──────────────────────────────────────
  {
    id: "legalist-officer",
    name: "Legalist Officer",
    englishName: "Legalist Officer",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["officer"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 3 },
    ],
    budget: 7,
    description: "On play: boost the allied unit with the lowest power by 3.",
  },
  {
    id: "qin-crossbow-formation",
    name: "Qin Crossbow Formation",
    englishName: "Qin Crossbow Formation",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["soldier", "crossbow"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
    ],
    budget: 7,
    description: "On play: deal 2 damage to a random enemy unit twice.",
  },
  // ── new cards ─────────────────────────────────────────────────────────────
  {
    id: "qin-spear-guard",
    name: "Qin Spear Guard",
    englishName: "Qin Spear Guard",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 4,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 4,
    description: "A reliable Qin spearman holding the front line.",
  },
  {
    id: "qin-siege-engineer",
    name: "Qin Siege Engineer",
    englishName: "Qin Siege Engineer",
    faction: "qin",
    type: "unit",
    row: "siege",
    power: 5,
    rarity: "common",
    tags: ["soldier", "engineer"],
    effects: [],
    budget: 5,
    description: "A Qin engineering specialist operating heavy siege weapons.",
  },
  {
    id: "qin-war-chariot",
    name: "Qin War Chariot",
    englishName: "Qin War Chariot",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 7,
    rarity: "elite",
    tags: ["cavalry", "chariot"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_LOWEST" }, amount: 2 },
    ],
    budget: 9,
    description: "On play: deal 2 damage to the enemy unit with the lowest power.",
  },
  {
    id: "qin-arbalest",
    name: "Qin Arbalest",
    englishName: "Qin Arbalest",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "elite",
    tags: ["soldier", "crossbow"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_HIGHEST" }, amount: 3 },
    ],
    budget: 9,
    description: "On play: deal 3 damage to the enemy unit with the highest power.",
  },
  {
    id: "shang-yang",
    name: "Shang Yang",
    englishName: "Shang Yang",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "hero",
    tags: ["strategist", "legalist"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_ROW", row: "melee" }, amount: 2 },
    ],
    budget: 11,
    description: "On play: boost all allied melee units by 2. The architect of Qin's power.",
  },
  {
    id: "bai-qi",
    name: "Bai Qi",
    englishName: "Bai Qi",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 9,
    rarity: "legend",
    tags: ["general"],
    effects: [
      { type: "DESTROY", target: { type: "ENEMY_LOWEST" } },
    ],
    budget: 13,
    description: "On play: destroy the enemy unit with the lowest power. The God of Slaughter.",
  },
  {
    id: "wang-jian",
    name: "Wang Jian",
    englishName: "Wang Jian",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 8,
    rarity: "hero",
    tags: ["general"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "SCORE_AHEAD" }, amount: 3 },
    ],
    budget: 11,
    description: "On play: if you are ahead on points, gain 3 power. A general who fights from strength.",
  },
  {
    id: "qin-cavalry-charge",
    name: "Qin Cavalry Charge",
    englishName: "Qin Cavalry Charge",
    faction: "qin",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["tactic", "cavalry"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
    ],
    budget: 8,
    description: "Deal 2 damage to a random enemy unit twice.",
  },
  {
    id: "qin-conscription",
    name: "Qin Conscription",
    englishName: "Qin Conscription",
    faction: "qin",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["policy", "token"],
    effects: [
      { type: "SUMMON", cardId: "qin-token", row: "melee", count: 2 },
    ],
    budget: 7,
    description: "Summon two Qin Conscripts to the melee row.",
  },
  {
    id: "qin-token",
    name: "Qin Conscript",
    englishName: "Qin Conscript",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 2,
    rarity: "common",
    tags: ["soldier", "token"],
    effects: [],
    budget: 2,
    description: "A summoned Qin conscript. Weak alone, dangerous in numbers.",
  },
];

// ---------------------------------------------------------------------------
// CHU (15 cards) — Swarm, token SUMMON, row BUFF, unit-count scaling.
// ---------------------------------------------------------------------------

const chuCards: CardDefinition[] = [
  // ── existing: pure bodies ─────────────────────────────────────────────────
  {
    id: "chu-spearman",
    name: "Chu Spearman",
    englishName: "Chu Spearman",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 4,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 4,
    description: "A modest Chu melee unit that supports swarm strategies.",
  },
  {
    id: "chu-archer",
    name: "Chu Archer",
    englishName: "Chu Archer",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "common",
    tags: ["soldier", "archer"],
    effects: [],
    budget: 4,
    description: "A basic Chu ranged unit for building board presence.",
  },
  // ── existing: skill cards (updated) ──────────────────────────────────────
  {
    id: "chu-shaman",
    name: "Chu Shaman",
    englishName: "Chu Shaman",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 3,
    rarity: "elite",
    tags: ["shaman"],
    effects: [
      { type: "SUMMON", cardId: "chu-token", row: "melee", count: 1 },
    ],
    budget: 7,
    description: "On play: summon one Chu Warrior to the melee row.",
  },
  {
    id: "chunshen-retainer",
    name: "Lord Chunshen's Retainer",
    englishName: "Lord Chunshen's Retainer",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["retainer"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_RANDOM", count: 2 }, amount: 1 },
    ],
    budget: 7,
    description: "On play: boost 2 random allied units by 1.",
  },
  {
    id: "xiang-yan",
    name: "Xiang Yan",
    englishName: "Xiang Yan",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "hero",
    tags: ["general"],
    effects: [
      {
        type: "CONDITIONAL_BOOST",
        condition: { type: "ALLY_UNIT_COUNT_AT_LEAST", count: 4 },
        amount: 3,
      },
    ],
    budget: 10,
    description: "On play: if you control 4 or more units, gain 3 power. Strength in numbers.",
  },
  // ── new cards ─────────────────────────────────────────────────────────────
  {
    id: "chu-footsoldier",
    name: "Chu Footsoldier",
    englishName: "Chu Footsoldier",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 4,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 4,
    description: "A basic Chu frontline soldier, one of many.",
  },
  {
    id: "chu-shield-bearer",
    name: "Chu Shield Bearer",
    englishName: "Chu Shield Bearer",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 5,
    description: "A Chu soldier with a heavy shield, holding the melee line.",
  },
  {
    id: "chu-river-guard",
    name: "Chu River Guard",
    englishName: "Chu River Guard",
    faction: "chu",
    type: "unit",
    row: "siege",
    power: 4,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 4,
    description: "A Chu defender positioned at river crossings.",
  },
  {
    id: "chu-war-dancer",
    name: "Chu War Dancer",
    englishName: "Chu War Dancer",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 3,
    rarity: "elite",
    tags: ["warrior"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 3 },
    ],
    budget: 7,
    description: "On play: boost the allied unit with the lowest power by 3.",
  },
  {
    id: "chu-herald",
    name: "Chu Herald",
    englishName: "Chu Herald",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 3,
    rarity: "elite",
    tags: ["support"],
    effects: [
      { type: "SUMMON", cardId: "chu-token", row: "melee", count: 1 },
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 1 },
    ],
    budget: 7,
    description: "On play: summon one Chu Warrior, then boost the weakest ally by 1.",
  },
  {
    id: "lord-chunshen",
    name: "Lord Chunshen",
    englishName: "Lord Chunshen",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 7,
    rarity: "hero",
    tags: ["general", "lord"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_ROW", row: "melee" }, amount: 1 },
    ],
    budget: 11,
    description: "On play: boost all allied melee units by 1. One of the Four Lords of the Warring States.",
  },
  {
    id: "king-of-chu",
    name: "King of Chu",
    englishName: "King of Chu",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 8,
    rarity: "legend",
    tags: ["king", "ruler"],
    effects: [
      {
        type: "CONDITIONAL_BOOST",
        condition: { type: "ALLY_UNIT_COUNT_AT_LEAST", count: 6 },
        amount: 4,
      },
    ],
    budget: 14,
    description: "On play: if you control 6 or more units, gain 4 power. The might of Chu unleashed.",
  },
  {
    id: "chu-battle-cry",
    name: "Chu Battle Cry",
    englishName: "Chu Battle Cry",
    faction: "chu",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["tactic", "token"],
    effects: [
      { type: "SUMMON", cardId: "chu-token", row: "melee", count: 2 },
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 1 },
    ],
    budget: 8,
    description: "Summon two Chu Warriors, then boost the weakest ally by 1.",
  },
  {
    id: "chu-flood-tactic",
    name: "Chu Flood Tactic",
    englishName: "Chu Flood Tactic",
    faction: "chu",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["tactic"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_ROW", row: "ranged" }, amount: 2 },
    ],
    budget: 7,
    description: "Boost all allied ranged units by 2.",
  },
  {
    id: "chu-token",
    name: "Chu Warrior",
    englishName: "Chu Warrior",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 2,
    rarity: "common",
    tags: ["soldier", "token"],
    effects: [],
    budget: 2,
    description: "A summoned Chu warrior. Small alone, overwhelming in a swarm.",
  },
];

// ---------------------------------------------------------------------------
// QI (15 cards) — DRAW_DISCARD hand management, DAMAGE enemy highest, planning.
// ---------------------------------------------------------------------------

const qiCards: CardDefinition[] = [
  // ── existing: pure body ───────────────────────────────────────────────────
  {
    id: "qi-warrior",
    name: "Qi Warrior",
    englishName: "Qi Warrior",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 6,
    description: "A sturdy Qi melee unit with solid baseline power.",
  },
  // ── existing: skill cards (updated) ──────────────────────────────────────
  {
    id: "jixia-scholar",
    name: "Jixia Scholar",
    englishName: "Jixia Scholar",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["scholar"],
    effects: [
      { type: "DRAW_DISCARD", draw: 1, discard: 1 },
    ],
    budget: 7,
    description: "On play: draw 1 card, then discard 1. Filter your hand for better options.",
  },
  {
    id: "guan-zhong-legacy",
    name: "Guan Zhong's Legacy",
    englishName: "Guan Zhong's Legacy",
    faction: "qi",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["policy"],
    effects: [
      { type: "DRAW_DISCARD", draw: 2, discard: 1 },
    ],
    budget: 7,
    description: "Draw 2 cards, then discard 1. The wisdom of Qi's greatest statesman.",
  },
  {
    id: "sun-bin",
    name: "Sun Bin",
    englishName: "Sun Bin",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 6,
    rarity: "hero",
    tags: ["strategist"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_HIGHEST" }, amount: 3 },
    ],
    budget: 10,
    description: "On play: deal 3 damage to the enemy unit with the highest power. A master of disruption.",
  },
  {
    id: "tian-ji",
    name: "Tian Ji",
    englishName: "Tian Ji",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "elite",
    tags: ["general"],
    effects: [
      { type: "DRAW_DISCARD", draw: 1, discard: 1 },
    ],
    budget: 8,
    description: "On play: draw 1 card, then discard 1. Renowned for strategic flexibility.",
  },
  // ── new cards ─────────────────────────────────────────────────────────────
  {
    id: "qi-spearman",
    name: "Qi Spearman",
    englishName: "Qi Spearman",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 5,
    description: "A dependable Qi front-line spearman.",
  },
  {
    id: "qi-crossbowman",
    name: "Qi Crossbowman",
    englishName: "Qi Crossbowman",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "common",
    tags: ["soldier", "crossbow"],
    effects: [],
    budget: 5,
    description: "A skilled Qi ranged unit with a powerful crossbow.",
  },
  {
    id: "qi-siege-crew",
    name: "Qi Siege Crew",
    englishName: "Qi Siege Crew",
    faction: "qi",
    type: "unit",
    row: "siege",
    power: 5,
    rarity: "common",
    tags: ["soldier", "engineer"],
    effects: [],
    budget: 5,
    description: "A Qi crew operating siege equipment at a distance.",
  },
  {
    id: "jixia-strategist",
    name: "Jixia Strategist",
    englishName: "Jixia Strategist",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "elite",
    tags: ["scholar", "strategist"],
    effects: [
      { type: "DRAW_DISCARD", draw: 2, discard: 1 },
    ],
    budget: 9,
    description: "On play: draw 2 cards, then discard 1. A senior Jixia Academy thinker.",
  },
  {
    id: "qi-scout",
    name: "Qi Scout",
    englishName: "Qi Scout",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 3,
    rarity: "elite",
    tags: ["scout"],
    effects: [
      { type: "DRAW_DISCARD", draw: 1, discard: 1 },
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 1 },
    ],
    budget: 7,
    description: "On play: draw 1, discard 1, and deal 1 damage to a random enemy.",
  },
  {
    id: "tian-dan",
    name: "Tian Dan",
    englishName: "Tian Dan",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "hero",
    tags: ["general"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_HIGHEST" }, amount: 3 },
      { type: "BUFF", target: { type: "SELF" }, amount: 1 },
    ],
    budget: 11,
    description: "On play: deal 3 damage to the enemy's strongest unit, then gain 1 power. Defender of Qi.",
  },
  {
    id: "sun-tzu",
    name: "Sun Tzu",
    englishName: "Sun Tzu",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "legend",
    tags: ["strategist", "scholar"],
    effects: [
      { type: "DRAW_DISCARD", draw: 2, discard: 1 },
      { type: "DAMAGE", target: { type: "ENEMY_HIGHEST" }, amount: 3 },
    ],
    budget: 13,
    description: "On play: draw 2 cards discard 1, then deal 3 damage to the strongest enemy. The Art of War personified.",
  },
  {
    id: "guan-zhong",
    name: "Guan Zhong",
    englishName: "Guan Zhong",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 6,
    rarity: "hero",
    tags: ["strategist", "official"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 2 },
      { type: "DRAW_DISCARD", draw: 1, discard: 1 },
    ],
    budget: 11,
    description: "On play: boost the weakest ally by 2, then draw 1 and discard 1. Qi's greatest prime minister.",
  },
  {
    id: "qi-iron-cavalry",
    name: "Qi Iron Cavalry",
    englishName: "Qi Iron Cavalry",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "elite",
    tags: ["cavalry"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_LOWEST" }, amount: 2 },
    ],
    budget: 8,
    description: "On play: deal 2 damage to the enemy unit with the lowest power.",
  },
  {
    id: "plan-of-jixia",
    name: "Plan of Jixia",
    englishName: "Plan of Jixia",
    faction: "qi",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["policy", "strategy"],
    effects: [
      { type: "DRAW_DISCARD", draw: 3, discard: 2 },
    ],
    budget: 8,
    description: "Draw 3 cards, then discard 2. Refresh your hand with Jixia precision.",
  },
];

// ---------------------------------------------------------------------------
// ZHAO (15 cards) — Comeback CONDITIONAL_BOOST, LOCK, cavalry BUFF, tempo.
// ---------------------------------------------------------------------------

const zhaoCards: CardDefinition[] = [
  // ── existing: pure body ───────────────────────────────────────────────────
  {
    id: "zhao-border-cavalry",
    name: "Zhao Border Cavalry",
    englishName: "Zhao Border Cavalry",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["cavalry"],
    effects: [],
    budget: 6,
    description: "A mobile Zhao cavalry unit with reliable melee strength.",
  },
  // ── existing: skill cards (updated) ──────────────────────────────────────
  {
    id: "hu-clothing-cavalry",
    name: "Hu Clothing Cavalry",
    englishName: "Hu Clothing Cavalry",
    faction: "zhao",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["cavalry", "tactic"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_ROW", row: "melee" }, amount: 1 },
    ],
    budget: 7,
    description: "Boost all allied melee units by 1. The cavalry reform that made Zhao feared.",
  },
  {
    id: "li-mu",
    name: "Li Mu",
    englishName: "Li Mu",
    faction: "zhao",
    type: "unit",
    row: "ranged",
    power: 8,
    rarity: "hero",
    tags: ["general"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "SCORE_BEHIND" }, amount: 3 },
    ],
    budget: 11,
    description: "On play: if you are losing on points, gain 3 power. Zhao's greatest defender.",
  },
  {
    id: "lian-po",
    name: "Lian Po",
    englishName: "Lian Po",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 9,
    rarity: "hero",
    tags: ["general"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "OPPONENT_PASSED" }, amount: 2 },
    ],
    budget: 11,
    description: "On play: if your opponent has passed this round, gain 2 power. A general who punishes hesitation.",
  },
  {
    id: "zhao-raid",
    name: "Zhao Raid",
    englishName: "Zhao Raid",
    faction: "zhao",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["raid", "tactic"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
    ],
    budget: 8,
    description: "Deal 2 damage to a random enemy unit twice. Swift and brutal.",
  },
  // ── new cards ─────────────────────────────────────────────────────────────
  {
    id: "zhao-footsoldier",
    name: "Zhao Footsoldier",
    englishName: "Zhao Footsoldier",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 5,
    description: "A sturdy Zhao foot soldier trained for the northern frontier.",
  },
  {
    id: "zhao-archer",
    name: "Zhao Archer",
    englishName: "Zhao Archer",
    faction: "zhao",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "common",
    tags: ["soldier", "archer"],
    effects: [],
    budget: 5,
    description: "A Zhao ranged unit skilled with the composite bow.",
  },
  {
    id: "zhao-siege-crew",
    name: "Zhao Siege Crew",
    englishName: "Zhao Siege Crew",
    faction: "zhao",
    type: "unit",
    row: "siege",
    power: 5,
    rarity: "common",
    tags: ["soldier", "engineer"],
    effects: [],
    budget: 5,
    description: "A Zhao crew managing catapults at the rear.",
  },
  {
    id: "zhao-heavy-cavalry",
    name: "Zhao Heavy Cavalry",
    englishName: "Zhao Heavy Cavalry",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 7,
    rarity: "elite",
    tags: ["cavalry"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "SCORE_BEHIND" }, amount: 2 },
    ],
    budget: 9,
    description: "On play: if you are losing on points, gain 2 power. Zhao cavalry at its fiercest when cornered.",
  },
  {
    id: "zhao-vanguard",
    name: "Zhao Vanguard",
    englishName: "Zhao Vanguard",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 4,
    rarity: "elite",
    tags: ["soldier"],
    effects: [
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 3 },
    ],
    budget: 7,
    description: "On play: boost the allied unit with the lowest power by 3.",
  },
  {
    id: "zhao-warlord",
    name: "Zhao Warlord",
    englishName: "Zhao Warlord",
    faction: "zhao",
    type: "unit",
    row: "ranged",
    power: 5,
    rarity: "elite",
    tags: ["officer"],
    effects: [
      { type: "LOCK", target: { type: "ENEMY_HIGHEST" } },
    ],
    budget: 8,
    description: "On play: lock the enemy unit with the highest power, disabling its skill.",
  },
  {
    id: "lin-xiangru",
    name: "Lin Xiangru",
    englishName: "Lin Xiangru",
    faction: "zhao",
    type: "unit",
    row: "ranged",
    power: 6,
    rarity: "hero",
    tags: ["diplomat", "official"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "SCORE_BEHIND" }, amount: 4 },
    ],
    budget: 10,
    description: "On play: if you are losing on points, gain 4 power. Zhao's defiant voice at the court of Qin.",
  },
  {
    id: "zhao-she",
    name: "Zhao She",
    englishName: "Zhao She",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 7,
    rarity: "hero",
    tags: ["general"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_LOWEST" }, amount: 3 },
    ],
    budget: 10,
    description: "On play: deal 3 damage to the enemy unit with the lowest power. Father of the warrior poet.",
  },
  {
    id: "king-of-zhao",
    name: "King of Zhao",
    englishName: "King of Zhao",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 9,
    rarity: "legend",
    tags: ["king", "ruler"],
    effects: [
      { type: "CONDITIONAL_BOOST", condition: { type: "SCORE_BEHIND" }, amount: 3 },
      { type: "BUFF", target: { type: "ALLY_LOWEST" }, amount: 2 },
    ],
    budget: 14,
    description: "On play: if losing, gain 3 power; then boost the weakest ally by 2. Zhao's last hope.",
  },
  {
    id: "zhao-ambush",
    name: "Zhao Ambush",
    englishName: "Zhao Ambush",
    faction: "zhao",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["tactic", "raid"],
    effects: [
      { type: "DAMAGE", target: { type: "ENEMY_RANDOM", count: 1 }, amount: 2 },
      { type: "LOCK", target: { type: "ENEMY_HIGHEST" } },
    ],
    budget: 8,
    description: "Deal 2 damage to a random enemy, then lock the enemy's strongest unit.",
  },
];

// ---------------------------------------------------------------------------
// Combined pool
// ---------------------------------------------------------------------------

export const INITIAL_CARDS: CardDefinition[] = [
  ...qinCards,
  ...chuCards,
  ...qiCards,
  ...zhaoCards,
];
