import type { CardDefinition } from "../types";

export const INITIAL_CARDS: CardDefinition[] = [
  {
    id: "qin-infantry",
    name: "Qin Infantry",
    englishName: "Qin Infantry",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 5,
    description: "A dependable Qin melee unit with straightforward power.",
  },
  {
    id: "qin-veteran",
    name: "Qin Veteran",
    englishName: "Qin Veteran",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 6,
    description: "A hardened Qin front-line unit built for steady pressure.",
  },
  {
    id: "iron-eagle-soldier",
    name: "Iron Eagle Soldier",
    englishName: "Iron Eagle Soldier",
    faction: "qin",
    type: "unit",
    row: "melee",
    power: 8,
    rarity: "elite",
    tags: ["soldier", "elite"],
    effects: [],
    budget: 8,
    description: "An elite Qin attacker with high standalone strength.",
  },
  {
    id: "legalist-officer",
    name: "Legalist Officer",
    englishName: "Legalist Officer",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["officer"],
    effects: [],
    budget: 7,
    description: "A Qin officer reserved for future allied-unit boost effects.",
  },
  {
    id: "qin-crossbow-formation",
    name: "Qin Crossbow Formation",
    englishName: "Qin Crossbow Formation",
    faction: "qin",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["soldier", "crossbow"],
    effects: [],
    budget: 8,
    description: "A ranged Qin formation reserved for future damage effects.",
  },
  {
    id: "chu-spearman",
    name: "Chu Spearman",
    englishName: "Chu Spearman",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 4,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 4,
    description: "A modest Chu melee unit that supports swarm strategies.",
  },
  {
    id: "chu-archer",
    name: "Chu Archer",
    englishName: "Chu Archer",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "common",
    tags: ["soldier", "archer"],
    effects: [],
    budget: 4,
    description: "A basic Chu ranged unit for building board presence.",
  },
  {
    id: "chu-shaman",
    name: "Chu Shaman",
    englishName: "Chu Shaman",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 3,
    rarity: "elite",
    tags: ["shaman"],
    effects: [],
    budget: 7,
    description: "A Chu support unit reserved for future summon effects.",
  },
  {
    id: "chunshen-retainer",
    name: "Lord Chunshen's Retainer",
    englishName: "Lord Chunshen's Retainer",
    faction: "chu",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["retainer"],
    effects: [],
    budget: 7,
    description: "A Chu court retainer reserved for future random ally buffs.",
  },
  {
    id: "xiang-yan",
    name: "Xiang Yan",
    englishName: "Xiang Yan",
    faction: "chu",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "hero",
    tags: ["general"],
    effects: [],
    budget: 10,
    description: "A Chu general intended to reward wide melee boards.",
  },
  {
    id: "qi-warrior",
    name: "Qi Warrior",
    englishName: "Qi Warrior",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["soldier"],
    effects: [],
    budget: 6,
    description: "A sturdy Qi melee unit with solid baseline power.",
  },
  {
    id: "jixia-scholar",
    name: "Jixia Scholar",
    englishName: "Jixia Scholar",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 4,
    rarity: "elite",
    tags: ["scholar"],
    effects: [],
    budget: 7,
    description: "A Qi scholar reserved for future draw and discard effects.",
  },
  {
    id: "guan-zhong-legacy",
    name: "Guan Zhong's Legacy",
    englishName: "Guan Zhong's Legacy",
    faction: "qi",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["policy"],
    effects: [],
    budget: 7,
    description: "A Qi policy card reserved for future hand filtering effects.",
  },
  {
    id: "sun-bin",
    name: "Sun Bin",
    englishName: "Sun Bin",
    faction: "qi",
    type: "unit",
    row: "ranged",
    power: 6,
    rarity: "hero",
    tags: ["strategist"],
    effects: [],
    budget: 10,
    description: "A Qi strategist reserved for future enemy disruption effects.",
  },
  {
    id: "tian-ji",
    name: "Tian Ji",
    englishName: "Tian Ji",
    faction: "qi",
    type: "unit",
    row: "melee",
    power: 5,
    rarity: "elite",
    tags: ["general"],
    effects: [],
    budget: 8,
    description: "A Qi commander intended for future behind-on-score filtering.",
  },
  {
    id: "zhao-border-cavalry",
    name: "Zhao Border Cavalry",
    englishName: "Zhao Border Cavalry",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 6,
    rarity: "common",
    tags: ["cavalry"],
    effects: [],
    budget: 6,
    description: "A mobile Zhao cavalry unit with reliable melee strength.",
  },
  {
    id: "hu-clothing-cavalry",
    name: "Hu Clothing Cavalry",
    englishName: "Hu Clothing Cavalry",
    faction: "zhao",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["cavalry", "tactic"],
    effects: [],
    budget: 7,
    description: "A Zhao tactic reserved for future cavalry boost effects.",
  },
  {
    id: "li-mu",
    name: "Li Mu",
    englishName: "Li Mu",
    faction: "zhao",
    type: "unit",
    row: "ranged",
    power: 8,
    rarity: "hero",
    tags: ["general"],
    effects: [],
    budget: 11,
    description: "A Zhao defender intended for future comeback boost effects.",
  },
  {
    id: "lian-po",
    name: "Lian Po",
    englishName: "Lian Po",
    faction: "zhao",
    type: "unit",
    row: "melee",
    power: 9,
    rarity: "hero",
    tags: ["general"],
    effects: [],
    budget: 11,
    description: "A Zhao veteran intended to punish opponents who pass early.",
  },
  {
    id: "zhao-raid",
    name: "Zhao Raid",
    englishName: "Zhao Raid",
    faction: "zhao",
    type: "special",
    power: 0,
    rarity: "elite",
    tags: ["raid", "tactic"],
    effects: [],
    budget: 8,
    description: "A Zhao raid tactic reserved for future random damage effects.",
  },
];
